dependencies:
    - name: cht-core
      version: 0.1.1
      repository: https://github.com/livinggoods/livinggoods-helm-charts
    - name: lg-couchdb
      version: 0.1.0
      repository: https://github.com/livinggoods/livinggoods-helm-charts