dependencies:
    - name: cht-core
      version: 0.1.1
      repository: https://livinggoods.github.io/livinggoods-helm-charts
    - name: lg-couchdb
      version: 0.1.0
      repository: https://livinggoods.github.io/livinggoods-helm-charts